name: docker-pipeline-aarthi
on: push
jobs:
  docker-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print your Register Number
        run: echo "Hello World - 22IT001"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Build
        run: docker build -t aarthi1015/ml-model-22IT001 .

      - name: Docker Images
        run: docker images
